### ISSUE TITLE
Page not found

### ISSUE THREAD

**Issue by gavinwye** [hmrc/design-patterns#104]
Prototype pattern for 404 pages: https://hmrc-design-patterns.herokuapp.com/pages/404-pages/index

## Todo
- [ ] refine content on main pattern page
- [ ] how should the header, in general, be displayed for 404 pages
- [ ] do 400 pages need a report a problem link?
- [ ] discuss enhancements for 404 as a service
- [ ] discuss header requirements for 404 pages
- [ ] should 404 pages have a signed in state
- [ ] add a second state to the form to tell people that it's been sent and let them know we will get back to them.

**Comment by alex16wake** [comment]
Our 400 error pages ask the user for information and this is submitted as a DeskPRO ticket for us to capture and try to resolve the problem

![image](https://user-images.githubusercontent.com/24815473/28574894-2f96bc36-7147-11e7-800a-7622838ac36c.png)

**Comment by stevenaproctor** [comment]
@alex16wake This is a great idea. The default screen in the frontend bootstrap says "Please check that you have entered the correct web address." But most people will not be typing in a URL, they will be selecting links or buttons.

**Comment by gavinwye** [comment]
Branch created on assets frontend for this pattern https://github.com/hmrc/assets-frontend/tree/%23104-404-page-pattern

**Comment by gavinwye** [comment]
@alex16wake @stevenaproctor yes that's a really good idea but we probably need to set users expectation about what we will do.

**Comment by MarkKeeling** [comment]
While we think this is a pattern, we would like to see UR to prove that users understood the information displayed.

**Comment by vickytnz** [comment]
The GDS pattern for the 'Is there anything wrong with this page?' pattern has 

> 'Don’t include personal or financial information like your National Insurance number or credit card details.' 

is there a reason that this is omitted? Does the system have sufficient safeguards to allow for this?

**Comment by stevenaproctor** [comment]
This is published in the [GOV.UK Design System](https://design-system.service.gov.uk/patterns/page-not-found-pages/). We have the Welsh version but there is no reason to keep a separate issue.
